### ISSUE TITLE
addTransaction is not defined

### ISSUE THREAD

**Issue by grncdr** [actualbudget/node-api#2]
I get the following error when requiring `@actual-app/api`:

```
ReferenceError: addTransaction is not defined
    at Object.<anonymous> (<snip>/node_modules/@actual-app/api/api.js:169:3)
```

**Comment by jlongster** [comment]
Sorry for not watching the issue - `addTransaction` shouldn't exist anymore. I can't remember if it did at one point and that's why this is confusing.

You should use [`addTransactions`](https://actualbudget.com/docs/developers/API/#addtransactions). The reason why the other doesn't exist is because it's best to import many at once and I want to encourage that.
